# Site settings
title: Andrew Healy | portfolio site
email: himself@andrewhealy.com
description: "{Art | Design | Development | Craft | Web} Andrew Healy portfolio site: commercial and personal projects"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stubbedtoe.github.io" # the base hostname & protocol for your site
github_username:  stubbedtoe
amazon_url: http://s3-eu-west-1.amazonaws.com/portfolio-ahealy
tumblr_username: virtualsurface
blog_address: http://virtualsurface.tumblr.com/
permalink: pretty
excerpt_separator: ""
collections:
  projects:
    output: true
    permalink: /projects/:path
  filter:
    output: true
    permalink: /filter/:path
defaults:
  -
    scope:
      path: "filter"
    values:
      layout: project_menu
  -
    scope:
      path: ""
    values:
      active: "all"
  -
    scope:
      path: "projects"
    values:
      long_title: false
      thumb: thumb.jpg
      layout: page
# Build settings
markdown: kramdown
exclude: 
  - js/main.js
  - _projects/no_publish
  - configuration.json
  - upload_files.py
  - process_images
  - contact.*
  - blog.*
gems:
  - jekyll-coffeescript
#  - susy
#don't compress during development
sass:
  style: compressed 